### ISSUE TITLE
Support to pass env variables to builder image from action.

### ISSUE THREAD

**Issue by fglaeser** [redhat-actions/s2i-build#16]
Nowadays the only way to pass env variables is using the .s2i/environment file. In some cases will be useful to support env variables from the step. e.g pass a secret value to builder image.

I'm trying to build a netcore app using s2i (as in OpenShift), so I have a nuget.config file in the repo, one of my sources is a private github repo, so in the nuget.config file I have a user and password. In order to no add the nuget token in the config file (For security reason), I use something like this.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <clear />
        <add key="nuget" value="https://api.nuget.org/v3/index.json" />
		<add key="github" value="https://nuget.pkg.github.com/PrivateREPO/index.json" />
    </packageSources>
   <packageSourceCredentials>
       <github>
            <add key="Username" value="USERNAME" />
            <add key="ClearTextPassword" value="%NUGET_REPO_PASSWORD%" />
        </github>
    </packageSourceCredentials>
</configuration>
```

So in my Openshift buildConfig I have a env variable with this value and everything works perfect but with this action I dont have this option. I can try to append this env variable to the .s2i/environment after checkout to avoid leave the token in the repo but I think it will be nice to have this option.

BR
Facundo

**Comment by tetchel** [comment]
You can put an `env` block in the `step` that uses this action, like

```
-  uses: redhat-actions/s2i-build@v1
    env: 
      NUGENT_REPO_PASSWORD: ${{ secrets.NUGENT_REPO_PASSWORD }}
    with: 
      - <your inputs>
```

does that solve your problem?

**Comment by fglaeser** [comment]
Nop, I've already tested that way and is not working.

Check the action and the log.

```
    - name: Setup and Build
      uses: redhat-actions/s2i-build@v1
      env:
        NUGET_REPO_PASSWORD: ${{ secrets.NUGENT_REPO_PASSWORD }}
      with:
        path_context: '.'
        builder_image: 'registry.access.redhat.com/ubi8/dotnet-31:3.1'
        image_name: sot-api
        image_tag: latest
        log_level: 5

```
Log from actions (only the env from .s2i/enviroment)

```
I1231 17:01:02.244847    2551 docker.go:970] Creating container with options {Name:"s2i_registry_access_redhat_com_ubi8_dotnet_31_3_1_8a5444b5" Config:{Hostname: Domainname: User: AttachStdin:false AttachStdout:true AttachStderr:false ExposedPorts:map[] Tty:false OpenStdin:true StdinOnce:true Env:[DOTNET_STARTUP_PROJECT=src/api/SotApi.csproj DOTNET_CONFIGURATION=Release DOTNET_RESTORE_CONFIGFILE=nuget.config DOTNET_RM_SRC=true DOTNET_PUBLISH_READYTORUN=true] Cmd:[/bin/sh -c tar -C /tmp -xf - && /usr/libexec/s2i/assemble] Healthcheck:<nil> ArgsEscaped:false Image:registry.access.redhat.com/ubi8/dotnet-31:3.1 Volumes:map[] WorkingDir: Entrypoint:[] NetworkDisabled:false MacAddress: OnBuild:[] Labels:map[] StopSignal: StopTimeout:<nil> Shell:[]} 

```

If I add the env in the file it works perfectly.

**Comment by Divyansh42** [comment]
Hey @fglaeser, We have tried to fix your problem in the PR #19 
Can you please check once if that suits your requirement else let us know the way you want, will try to figure out that.

**Comment by Divyansh42** [comment]
Hey @fglaeser , here is the possible solution.
```yaml
 - name: Setup and Build
    uses: redhat-actions/s2i-build@v1
    env:
      NUGET_REPO_PASSWORD: ${{ secrets.NUGENT_REPO_PASSWORD }}
    with:
      path_context: '.'
      builder_image: 'registry.access.redhat.com/ubi8/dotnet-31:3.1'
      image_name: sot-api
      image_tag: latest
      log_level: 5
      env_file: nugent.config 
```
`env_file` will take s2i env file that we want to use as .s2i/envoirnment and you can pass the required secrets in the env as:
```
env:
   NUGET_REPO_PASSWORD: ${{ secrets.NUGENT_REPO_PASSWORD }}
```
Please take a look at this and let us know if this solves your problem. We will go ahead implementing this design.

**Comment by fglaeser** [comment]
Sorry but I've checked the PR and it is a little bit different of the solution suggested in your previous comment.

Your previous comment:
```
 - name: Setup and Build
    uses: redhat-actions/s2i-build@v1
    env:
      NUGET_REPO_PASSWORD: ${{ secrets.NUGENT_REPO_PASSWORD }}
    with:
      path_context: '.'
      builder_image: 'registry.access.redhat.com/ubi8/dotnet-31:3.1'
      image_name: sot-api
      image_tag: latest
      log_level: 5
      env_file: nugent.config  <-----------------

``` 
What I saw in the PR.

```
 - name: Setup and Build
    uses: redhat-actions/s2i-build@v1
    with:
      path_context: '.'
      builder_image: 'registry.access.redhat.com/ubi8/dotnet-31:3.1'
      image_name: sot-api
      image_tag: latest
      log_level: 5
      env_vars:              <-----------------------------------
           NUGET_REPO_PASSWORD: ${{ secrets.NUGET_REPO_PASSWORD }}

```

is it correct?

**Comment by tetchel** [comment]
after the PR was submitted, I proposed the first design (`env_file`) because the PR design (`env_vars`) would require you to copy each of the variables you wanted out of your env file, rather than just using the already-existing env file.

do you have a preference between the two designs?

**Comment by fglaeser** [comment]
@tetchel if you can put the environment variables in the `env` section of the action together with the env vars in the `.s2i/environment` file, for me is enough. 

```
 - name: Setup and Build
    uses: redhat-actions/s2i-build@v1
    env:
      NUGET_REPO_PASSWORD: ${{ secrets.NUGENT_REPO_PASSWORD }}
    with:

```
Because my `nuget.config` is not a file with environment variables is just a config file where I need the value of an env var.
 I only need the env vars in the env section as env vars in the image builder.
