### ISSUE TITLE
How to use runtime image?

### ISSUE THREAD

**Issue by fglaeser** [redhat-actions/s2i-build#17]
Is there a way to use runtime image? I'am building a netcore3.1 application using this

```
    - name: Setup and Build
      uses: redhat-actions/s2i-build@v1
      with:
        path_context: '.'
        builder_image: 'registry.access.redhat.com/ubi8/dotnet-31:3.1'
        image_name: poc-cicd/api
        image_tag: latest
        log_level: 5
```
But the final image is 774 mb, so I assume there is no runtime image involve in the process. how can I achieve that in order to reduce the size of my final image?

Thanks

**Comment by fglaeser** [comment]
I finally used something like this.


```
    - name: Publish
      run: dotnet publish -c Release -o ./artifacts --nologo
    - name: Build Runtime Image
      uses: redhat-actions/s2i-build@v1
      with:
        path_context: './artifacts'
        builder_image: 'registry.access.redhat.com/ubi8/dotnet-31-runtime:3.1'
        image_name: poc-cicd/api
        image_tag: latest

```
