### ISSUE TITLE
[FEATURE] Private builder images (such as registry.redhat.io)

### ISSUE THREAD

**Issue by jteemsfi** [redhat-actions/s2i-build#39]
### Is your feature request related to a problem? Please describe.

I'd like to be able to use non-public builder images with s2i. A perfect example is being able to use images from registry.redhat.io that we have access to.

### Describe the solution you'd like

The best option would be the ability to pass in the credentials to the action from GitHub Secrets to authenticate before building (similar to how the podman actions work).

### Describe alternatives you've considered

An alternative I thought would work was to use the `redhat-actions/podman-login@v1` action before calling the s2i-build action. The login in my example workflow worked but the s2i-build action was still unable to pull.

### Additional context

```yaml
---
name: Image Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Log in to registry.redhat.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.RH_USER }}
          password: ${{ secrets.RH_PASS }}
          registry: registry.redhat.io
      - name: Source to Image Build
        uses: redhat-actions/s2i-build@v2
        with:
          builder_image: 'registry.redhat.io/jboss-eap-7/eap74-openjdk11-openshift-rhel8:7.4.1'
          image: ${{ github.event.repository.name }}
          tags: latest
```

```
Run redhat-actions/podman-login@v1
  with:
    username: ***
    password: ***
    registry: registry.redhat.io
    logout: true
/usr/bin/podman version
  /usr/bin/podman version
  Version:      3.4.2
  API Version:  3.4.2
  Go Version:   go1.16.6
  Built:        Thu Jan  1 00:00:00 1970
  OS/Arch:      linux/amd64
/usr/bin/podman login registry.redhat.io -u *** -p ***
Login Succeeded!
✅ Successfully logged in to registry.redhat.io as ***
Exporting REGISTRY_AUTH_FILE=/tmp/podman-run-1001/containers/auth.json





Run redhat-actions/s2i-build@v2
⏳ s2i is not installed. Installing s2i v1.3.1
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/de7dcfe5-4277-4fac-9dab-275cacac9b39 -f /home/runner/work/_temp/6de9fd4a-7843-407f-b98d-20a2ddf9594d
✅ Sucessfully installed s2i.
/home/runner/work/_temp/de7dcfe5-4277-4fac-9dab-275cacac9b39/s2i build . registry.redhat.io/jboss-eap-7/eap74-openjdk11-openshift-rhel8:7.4.1 epb-customer:latest --loglevel 1
Running S2I version "v1.3.1"
Image "registry.redhat.io/jboss-eap-7/eap74-openjdk11-openshift-rhel8:7.4.1" not available locally, pulling ...
pulling image error : Error response from daemon: Head "https://registry.redhat.io/v2/jboss-eap-7/eap74-openjdk11-openshift-rhel8/manifests/7.4.1": unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/articles/3399531
Image "registry.redhat.io/jboss-eap-7/eap74-openjdk11-openshift-rhel8:7.4.1" not available locally, pulling ...
pulling image error : Error response from daemon: Head "https://registry.redhat.io/v2/jboss-eap-7/eap74-openjdk11-openshift-rhel8/manifests/7.4.1": unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/articles/3399531
ERROR: An error occurred: unable to get registry.redhat.io/jboss-eap-7/eap74-openjdk11-openshift-rhel8:7.4.1
ERROR: Suggested solution: check image name, or if using a local image set the builder image pull policy to "never"
Details: Error response from daemon: Head "https://registry.redhat.io/v2/jboss-eap-7/eap74-openjdk11-openshift-rhel8/manifests/7.4.1": unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/articles/3399531
ERROR: If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/docs. Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from your build using log output level 3.
Error: Error: s2i exited with code 2
Running S2I version "v1.3.1"
Image "registry.redhat.io/jboss-eap-7/eap74-openjdk11-openshift-rhel8:7.4.1" not available locally, pulling ...
pulling image error : Error response from daemon: Head "https://registry.redhat.io/v2/jboss-eap-7/eap74-openjdk11-openshift-rhel8/manifests/7.4.1": unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/articles/3399531
Image "registry.redhat.io/jboss-eap-7/eap74-openjdk11-openshift-rhel8:7.4.1" not available locally, pulling ...
pulling image error : Error response from daemon: Head "https://registry.redhat.io/v2/jboss-eap-7/eap74-openjdk11-openshift-rhel8/manifests/7.4.1": unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/articles/3399531
ERROR: An error occurred: unable to get registry.redhat.io/jboss-eap-7/eap74-openjdk11-openshift-rhel8:7.4.1
ERROR: Suggested solution: check image name, or if using a local image set the builder image pull policy to "never"
Details: Error response from daemon: Head "https://registry.redhat.io/v2/jboss-eap-7/eap74-openjdk11-openshift-rhel8/manifests/7.4.1": unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/articles/3399531
ERROR: If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/docs. Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from your build using log output level 3.
```
